# Generated by Django 3.1.3 on 2020-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('url', models.URLField()),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('approve_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
